# Generated by Django 5.0.3 on 2024-04-10 08:34

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_banner_directory_path, verbose_name='banner_picture'),
        ),
    ]
