# Generated by Django 5.0.3 on 2024-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_website_alter_restaurant_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[(1, 'Thai Food'), (2, 'Asia Food'), (3, 'Indian Food'), (4, 'French Food'), (5, 'Mexican Food'), (6, 'Italian Food')], max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant_directory_path'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.IntegerField(choices=[(1, '$'), (2, '$$'), (3, '$$$')], default=1),
            preserve_default=False,
        ),
    ]
