# Generated by Django 5.0.3 on 2024-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurant_category_alter_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(1, 'Thai Food'), (2, 'Asia Food'), (3, 'Indian Food'), (4, 'French Food'), (5, 'Mexican Food'), (6, 'Italian Food')]),
        ),
    ]
