# Generated by Django 5.0.3 on 2024-04-10 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
