# Generated by Django 5.0.3 on 2024-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationprofile',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
